name: Build ImmortalWrt for Lyt T68M (tar.gz for Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone ImmortalWrt repository
        run: |
          git clone https://github.com/immortalwrt/immortalwrt.git
          cd immortalwrt
          git checkout openwrt-24.10  # 使用稳定版分支，推荐 24.10

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libncurses5-dev \
            python3 \
            python3-pip \
            python3-pyelftools \
            libssl-dev \
            xsltproc \
            libelf-dev \
            cpio \
            zlib1g-dev \
            gawk \
            git \
            wget \
            unzip \
            file \
            subversion \
            gettext \
            time \
            gcc-multilib \
            g++-multilib \
            quilt \
            perl-base \
            perl-modules

      - name: Set up Python dependencies
        run: |
          sudo pip3 install ply

      - name: Update and install feeds
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build for Lyt T68M
        run: |
          cd immortalwrt
          # 配置 Rockchip RK3568 架构和 Lyt T68M 设备
          cat << EOF > .config
          CONFIG_TARGET_rockchip=y
          CONFIG_TARGET_rockchip_armv8=y
          CONFIG_TARGET_rockchip_armv8_DEVICE_lyt_t68m=y  # Lyt T68M 设备配置文件
          CONFIG_BUILD_NLS=y
          CONFIG_IMAGEOPT=y
          CONFIG_KERNEL_INITRAMFS=y  # 启用 initramfs
          CONFIG_TARGET_ROOTFS_TARGZ=y  # 确保生成 tar.gz
          CONFIG_TARGET_ROOTFS_SQUASHFS=n  # 禁用 squashfs，专注于 tar.gz
          CONFIG_TARGET_ROOTFS_EXT4FS=n  # 禁用 ext4fs
          # 常用软件包（适合 Docker 环境）
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_ca-certificates=y
          CONFIG_PACKAGE_docker=y
          CONFIG_PACKAGE_dockerd=y
          CONFIG_PACKAGE_luci-app-docker=y
          # 网络和工具包（可选）
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_nano=y
          CONFIG_PACKAGE_iptables=y
          CONFIG_PACKAGE_kmod-nf-nat=y
          EOF
          make defconfig

      - name: Build firmware
        run: |
          cd immortalwrt
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-lyt-t68m
          path: immortalwrt/bin/targets/rockchip/armv8/*.tar.gz
          retention-days: 5
