```yaml
name: Build Nikki for ARM64 on OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout OpenWrt source code
    - name: Checkout OpenWrt
      uses: actions/checkout@v4
      with:
        repository: openwrt/openwrt
        ref: v23.05.5  # Use a stable OpenWrt release, adjust as needed
        path: openwrt

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses5-dev libssl-dev python3 rsync unzip zlib1g-dev file wget \
          libdeflate-dev libdeflate0

    # Update and install feeds
    - name: Update and install feeds
      working-directory: openwrt
      run: |
        echo "src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a -p nikki

    # Configure OpenWrt for ARM64
    - name: Configure OpenWrt
      working-directory: openwrt
      run: |
        cat << EOF > .config
        CONFIG_TARGET_rockchip=y
        CONFIG_TARGET_rockchip_armv8=y
        CONFIG_TARGET_rockchip_armv8_DEVICE_generic=y
        CONFIG_PACKAGE_luci-app-nikki=y
        CONFIG_PACKAGE_kmod-tun=y
        CONFIG_PACKAGE_lua=y
        EOF
        make defconfig

    # Compile host tools (including libdeflate)
    - name: Compile host tools
      working-directory: openwrt
      run: |
        make tools/libdeflate/compile -j$(nproc) V=s
        make tools/install -j$(nproc) V=s

    # Compile Nikki
    - name: Compile Nikki
      working-directory: openwrt
      run: |
        make package/luci-app-nikki/compile -j$(nproc) V=s

    # Upload artifacts
    - name: Upload Nikki artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nikki-arm64-packages
        path: openwrt/bin/packages/aarch64_cortex-a53/nikki/
        retention-days: 5
```
